### ISSUE TITLE
Alternate frontend overhaul

### ISSUE THREAD

**Issue by ballista01** [shashank6341/soen-6611#14]
- Correct usage of the Statistics class
- Remove numpad
- Clear input feature
- Implement save to history and load from history
- Implement load from user specified csv path
- Make statistics optional to save calculation time according to different types of user.

**Comment by ballista01** [comment]
PR: https://github.com/shashank6341/soen-6611/pull/15

**Comment by shashank6341** [comment]
Merged and Fixed.
